### ISSUE TITLE
Any call reports "login first"

### ISSUE THREAD

**Issue by sanchosk** [rytilahti/python-ubus#7]
I can see this is quite old code, but it seems to be still in use with success by Home Assistant, so I'll try to ask for help anyhow.

I tried using the lib with python 3.12. After successful install, I am able to do:
`from ubus import Ubus`
and then login using
```
ubus = Ubus('192.168.1.1')
ubus['session']['login'](username='root', password='xxx')
```
I get a lot of info, including session ID, timeout 300 seconds, lots of access-gourps, ... And it seems to also accept my custom config for Home assistant as it reports access group 'hass' as read - so far so good.
But then, when I try
`print(ubus['dhcp']['ipv4leases']())`
I get error message 
`UbusException("Access denied with empty session, please login() first." % response)`

Any idea what am I doing wrong?

**Comment by sanchosk** [comment]
Closing - wrong config on my end, your library works great! Sorry for the confusion.
Now requests like `leases = ubus['luci-rpc']['getDHCPLeases']()` return actual list of DHCP leases, as expected. Thanks again!

**Comment by rytilahti** [comment]
Hi @sanchosk, note, that I don't think this library is used in homeassistant as this was never packaged. This project was one of my first tries to do something useful in Python, and didn't really gain momentum, but glad to hear it still works! :-)

**Comment by sanchosk** [comment]
It looks to me like it is used by integration called OpenWrt(ubus).
I also installed it manually, it's very useful and works great.
So take this as a big thanks from me...
I'll check the sources of HA to see if they use different lib then.

**Comment by sanchosk** [comment]
5 minutes of code-reading and you are right :(
They are using https://pypi.org/project/openwrt-ubus-rpc/

**Comment by rytilahti** [comment]
Ah, yes, indeed. That library is less generic and specifically supports only a very small set of commands that are necessary for the homeassistant integration, so there's still value in this library if someone is doing something else :-)
